databases:
  - name: berakah-db
    databaseName: berakah_emeth
    user: berakah_user
    plan: starter

services:
  - type: web
    name: berakah-emeth
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: berakah-db
          property: connectionString
